name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=2.0.1 
  - scikit-learn=0.24.1
  - matplotlib 
  - pillow=8.1.2
  - pytest=6.2.2
  - scipy=1.5.2
  - pip:
        - wandb==0.10.21
        - hydra-joblib-launcher==1.1.2
        - databricks-cli
        - mlflow==2.8.1