name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 
  - pip=20.3.3
  - requests=2.24.0
  - scikit-learn=0.24.1
  - matplotlib 
  - pillow=8.1.2
  - pyyaml
  -jupyterlab=4.0.9
  - pip:
      - mlflow==2.8.1
      - wandb==0.10.21
      - hydra-joblib-launcher==1.1.2
      - databricks-cli 
      - pandas=1.1.4
      - mlflow=2.0.1 
      - hydra-core=1.3.2