name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - hydra-core=1.3.2
  - pip=20.3.3
  - mlflow=2.0.1 
  - requests=2.24.0
  - scikit-learn=0.24.1
  - pandas=1.1.4
  - matplotlib 
  - pillow=8.1.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.10.21
      - hydra-joblib-launcher==1.1.2
      - databricks-cli 
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
      name: basic_cleaning 